<footer>
	<div class="footer-contact">
		<a title="ixleeds email address for further information" href="mailto:info@ixleeds.net">info@ixleeds.net</a><br/>
		Leeds, West Yorkshire LS10 1JW
	</div>
	<div class="social-block">
		<!--a class="fb" href="http://www.facebook.com/groups/151543478199614/" title="facebook contact details" target="_blank">Facebook</a>
		<a class="linked" href="http://www.linkedin.com/groups?mostPopular=&gid=3400377"  title="linked contact details" target="_blank">LinkedIn</a-->
		<a class="tw" href="http://twitter.com/ixleeds"  title="twitter contact details" target="_blank">Twitter</a>
	</div>
</footer>
