<style type="text/css">
.menu {
   float:left;
   width:100%;
   background:#fff;
   border-bottom:4px solid #000;
   overflow:hidden;
   position:relative;
}

.menu ul {
   clear:left;
   float:left;
   list-style:none;
   margin:0;
   padding:0;
   position:relative;
   left:50%;
   text-align:center;
}
 
.menu ul li {
   font-family:Arial, Helvetica, sans-serif;
   font-weight:normal;
   display:block;
   float:left;
   list-style:none;
   margin:0;
   padding:0;
   position:relative;
   right:50%;
}
 
.menu ul li a {
   display:block;
   margin:0 0 0 1px;
   padding:3px 10px;
   background:#aaa;
   color: white;
   text-decoration:none;
   line-height:1.3em;
}
 
.menu ul li a:visited {
}
 
.menu ul li a:hover, .menu ul li .current {
   color: #fff;
   background-color:#0b75b2;
}
</style>

<div class="menu">
<ul>
	<li/><a href="/index.html">Home</a>
	<li/><a href="/content/about.html">About Us</a>
	<li/><a href="/content/join.html">Join Us</a>
	<li/><a href="/content/members.html">Members</a>
	<li/><a href="/content/outreach.html">Outreach</a>
	<li/><a href="/event/index.html">Event</a>
</ul>
<br style="clear:left"/>
</div>
