<!--<img src="/img/member/aql.jpg" alt="aql">
<img src="/img/member/akamai.jpg" alt="Akamai">
<img src="/img/member/ask4.jpg" alt="ask4">
<img src="/img/member/bytemark.jpg" alt="Bytemark">
<img src="/img/member/axa-network.jpg" alt="Exa Networks">
<img src="/img/member/fluidata.jpg" alt="Fluidata">
<img src="/img/member/ixreach.jpg" alt="">
<img src="/img/member/vaioni.jpg" alt="">
<img src="/img/member/8.jpg" alt="">
<img src="/img/member/cable-wireless.jpg" alt="">
<img src="/img/member/york-data-services.jpg" alt="">-->
<a class="member-image" href="http://www.aql.com" target="aql"><img src="/images/logo/member/aql.jpg" alt="aql" /></a>
<a class="member-image" href="http://www.akamai.com" target="akamai"><img src="/images/logo/member/akamai.jpg" alt="Akamai" /></a>
<a class="member-image" href="http://www.ask4.com/" target="ask4"><img src="/images/logo/member/ask4.jpg" alt="ask4" /></a>
<a class="member-image" href="http://www.bytemark.co.uk" target="bytemark"><img src="/images/logo/member/bytemark.jpg" alt="Bytemark" /></a>
<a class="member-image" href="http://www.exa-networks.co.uk/" target="exa"><img src="/images/logo/member/exa.jpg" alt="Exa Networks" /></a>
<!--a class="member-image" href="http://www.fluidata.co.uk/" target="fluidata"><img src="/images/logo/member/fluidata.jpg" alt="Fluidata" /></a-->
<a class="member-image" href="http://www.ixreach.net" target="ixreach"><img src="/images/logo/member/ixreach.jpg" alt="IXReach" /></a>
